language: node_js
node_js:
- '16'
services:
- docker
notifications:
  email: false
  slack:
    rooms:
      secure: bVTOD/N1cvVIpeXbcKR05yUhrkVT60dJlj6vhWO827N4jBsghSOWYaN347LLbjYZhPscv6Gg24BTaY809oSH+1gcfUuWHOKpQAgHCML0wDwmK3u7GfKuNDmFUT4ySwyxR2nwM/HriAakDtAKjisrZKCBEDHJMnS0b4Nl06XYGME2AS7nm61nAj/VfBZwnNurBweGK6Z50U+tCdAv0tM5scCAfSCtYDE0L53g4g/8kbQ4xMLQgRQ6OFNa0zYSs/TPzldXbEFiVyME6g6JKs/7J7sIupoheugevQ/Ym9IXzxzZx7ralnk3GS9GyL+Eio83cyzoeiaWIzwiC13OiBy5Up781bcSVKtY4NYFAhEDTm1Pqi14COcsSSjOyNDlHWsO8+BAntOvCnygQjN5SafJEg98mztbp8BCPV3FS6QRL0FyjuGuaWjQ1/08KMS0zJ9ZSzeMpY6T2Lbws/oyytrPkhPFfYgV8Kh0uMP+yBIUOj6L1szULFq6AhurAY3dKJx/sL905WFZXIYRZuadGQ12eAW/P2ck2keyk6m6T5NQLZPykJm1dpg7MJ1efhNKM+G0kD9mleP1iBXoNG67JRgx60cTb31bDA+ZcZFvf66uUdxGbksWUzxoVB4Ce+Mg09wHpS1ER93L6j/OaiFtZLXF9i1Iak1ph7AsLVcZp5yCvmM=
    on_success: always
    on_failure: always
env:
- JOB=stations
- JOB=observations
before_script:
- docker login -u="$DOCKER_USER" -p="$DOCKER_PASSWORD"
script:
- |
  REPO_SLUG="$TRAVIS_REPO_SLUG"
  IMAGE_NAME=${REPO_SLUG,,} # to lowercase
  if [[ -z "$TRAVIS_TAG" ]]; then
    IMAGE_TAG=latest
    KRAWLER_TAG=latest
  else
    IMAGE_TAG=$(node -p -e "require('./package.json').version")
    KRAWLER_TAG=$(node -p -e "require('./package.json').peerDependencies['@kalisio/krawler']")
  fi
  docker build --build-arg KRAWLER_TAG=$KRAWLER_TAG -f dockerfile."$JOB" -t $IMAGE_NAME:"$JOB"-$IMAGE_TAG .
deploy:
  provider: script
  script: docker push $IMAGE_NAME:"$JOB"-$IMAGE_TAG
  on:
    all_branches: true
